Automated rollback of changelist 149471686.
*** Reason for rollback ***

Build errors, e.g.

javascript/closure/dom/dom.js:730: ERROR - inconsistent return type
found : (Window|null)
required: Window
return doc.parentWindow || doc.defaultView;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

*** Original change description ***

Improve typing of Document.defaultView and make CSSStyleDeclaration iterable.

It unblocks some projects to use BanUnknownTypedClassPropsReferences conformance check.

***

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=149477892