Automated g4 rollback of changelist 225077857.
*** Reason for rollback ***

Breaks polymer app builds:

java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

GETELEM 7879 [length: 28] [source_file: blaze-out/k8-opt/bin/third_party/javascript/polygerrit/gr-app-w.js]
  Node(EXPR_RESULT): blaze-out/k8-opt/bin/third_party/javascript/polygerrit/gr-app-w.js:7879:0
this._instanceProps[this.as] = true;
  Parent(BLOCK): blaze-out/k8-opt/bin/third_party/javascript/polygerrit/gr-app-w.js:7877:19
ready: function () {

[...]
Caused by: java.lang.IllegalArgumentException: GETELEM 7879 [length: 28] [source_file: blaze-out/k8-opt/bin/third_party/javascript/polygerrit/gr-app-w.js]
        ... 43 more

*** Original change description ***

Preserve Polymer calls in .i.js files

***

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=225095379