Removed TextTrackMode enum.
The enum causes type mismatch for existing code:

wireless/android/video/lava/cinder/html5_vtt/handlers/tts_track_renderer.js:54: ERROR - assignment to property mode of TextTrack
found   : string
required: TextTrackMode<string>

and the enum is not actually defined by the browser.

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=131640626