Add type annotation (@const) to prevent Closure compiler errors.
Without those, I get the following errors:

contrib/externs/chrome_extensions.js:5057: ERROR - assignment to property platformKeys of chrome
found   : {}
required: {
  ClientCertificateSelectDetails: function(this:chrome.platformKeys.ClientCertificateSelectDetails): ?,
  ClientCertificateSelectRequestDetails: function(this:chrome.platformKeys.ClientCertificateSelectRequestDetails): ?,
  Match: function(this:chrome.platformKeys.Match): ?,
  SelectCertificateDetailRequest: None,
  SelectCertificateDetails: None,
  ServerCertificateVerificationDetails: function(this:chrome.platformKeys.ServerCertificateVerificationDetails): ?,
  ServerCertificateVerificationResult: function(this:chrome.platformKeys.ServerCertificateVerificationResult): ?,
  VerifyServerCertificateDetails: None,
  getKeyPair: function(?, ?, ?): ?,
  selectClientCertificates: function(?, ?): ?, ...
}
chrome.platformKeys = {};
^^^^^^^^^^^^^^^^^^^^^^^^

contrib/externs/chrome_extensions.js:5138: ERROR - assignment to property power of chrome
found   : {}
required: {releaseKeepAwake: function(): ?, requestKeepAwake: function(?): ?}
chrome.power = {};
^^^^^^^^^^^^^^^^^

contrib/externs/chrome_extensions.js:6683: ERROR - assignment to property types of chrome
found   : {}
required: {
  ChromeSetting: function(this:chrome.types.ChromeSetting): ?,
  ChromeSettingChangedEvent: function(this:chrome.types.ChromeSettingChangedEvent): ?,
  ChromeSettingClearDetails: function(this:chrome.types.ChromeSettingClearDetails): ?,
  ChromeSettingGetDetails: function(this:chrome.types.ChromeSettingGetDetails): ?,
  ChromeSettingGetResultDetails: function(this:chrome.types.ChromeSettingGetResultDetails): ?,
  ChromeSettingSetDetails: function(this:chrome.types.ChromeSettingSetDetails): ?,
  DetailsCallback: None,
  ImageDetails: None
}
chrome.types = {};
^^^^^^^^^^^^^^^^^

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=230372019