Fix build error caused by excluding browser externs from typedast.bzl
src/com/google/javascript/jscomp/js/util/eventlistener.js:121:25: ERROR - [JSC_POSSIBLE_INEXISTENT_PROPERTY] Property handleEvent never defined on listener

This property is accessed on a "loose" type, but is not defined anywhere in the program, so it must not exist.
  121|         var h = listener.handleEvent;
                                ^^^^^^^^^^^

--env=CUSTOM passes only core language externs, but the default is to include browser externs.
PiperOrigin-RevId: 833582879