Fix missing trailing newline in piper-cut-cl.json
If this fixes the following GitHub actions workflow error, I'll update the release automation to add the newline.

https://github.com/google/closure-compiler/actions/runs/13575409019/job/37950319882

Run {
  {
      echo 'piperJson<<EOF'
      cat ./.github/piper-cut-cl.json
      echo EOF
  } >> "$GITHUB_OUTPUT"
  shell: /usr/bin/bash -e {0}
  env:
    VERSION_NODEJS: 16.16.0
    UNSYMLINK_DIR: bazel-bin-unsymlink
Error: Unable to process file command 'output' successfully.
Error: Invalid value. Matching delimiter not found 'EOF'
PiperOrigin-RevId: 731857175